name: Build & Test

on:
  pull_request:
    branches: [ 'master' ]

env:
  IMAGE_NAME_FRONTEND_TAG: ${{ github.repository }}/client:test
  IMAGE_NAME_BACKEND_TAG: ${{ github.repository }}/server:test
  PORT: 3001
  REBUILD: true
  DB_USER: root
  DB_PW: ''
  DB_NAME: buergerbuero
  DB_HOST: 127.0.0.1
  AMQPHOST: ''
  RABBITMQEXCHANGE: ''
  JWT_SECRET: TEST
  MAIN_HUB_HOST: ''
  SKIP_AUTH: true
  FRONTEND_HOST: ''

jobs:
  buildFrontend:
    name: '[FRONTEND] Build & Test'
    runs-on: ubuntu-latest
    steps:
      - name: Frontend Env to Lowercase
        run: |
          echo "FRONTEND_TAG=${IMAGE_NAME_FRONTEND_TAG,,}">>${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ./client
          load: true
          tags: ${{ env.FRONTEND_TAG }}
          
  buildBackend:
    name: '[BACKEND] Build & Test'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: buergerbuero
          MYSQL_HOST: 127.0.0.1
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s 
    steps:
      - name: Backend Env to Lowercase
        run: |
          echo "BACKEND_TAG=${IMAGE_NAME_BACKEND_TAG,,}">>${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Change auth plugin for root
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -e "ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '';FLUSH PRIVILEGES;"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          
      - run: cd ./server;npm ci
      - run: cd ./server;npm test
        
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ./server
          load: true
          tags: ${{ env.BACKEND_TAG }}
